/*
 Copyright (C) 2009 by Kyle Poole <kyle.poole@gmail.com>
 Part of the Battle for Wesnoth Project http://www.wesnoth.org/
 
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License version 2
 or at your option any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY.
 
 See the COPYING file for more details.
 */

#ifndef UNIT_TEXTURE_ATLAS_INCLUDED
#define UNIT_TEXTURE_ATLAS_INCLUDED


#include "TextureAtlas.h"

// handle image modifications, eg "~RC(magenta>1)" means it should change the magenta to the red team color
#define UNIT_COLOR_RED			1
#define UNIT_COLOR_BLUE			2
#define UNIT_COLOR_GREEN		3
#define UNIT_COLOR_PURPLE		4
#define UNIT_COLOR_BLACK		5
#define UNIT_COLOR_BROWN		6
#define UNIT_COLOR_ORANGE		7
#define UNIT_COLOR_WHITE		8
#define UNIT_COLOR_TEAL			9

// paths are like units/elves-wood/fighter.png
#define UNITMAP_DRAKES_DRAKES		100
#define UNITMAP_DRAKES_ARMAGEDDON	110
#define UNITMAP_DRAKES_BLADEMASTER	120
#define UNITMAP_DRAKES_BURNER		130
#define UNITMAP_DRAKES_CLASHER		140
#define UNITMAP_DRAKES_ENFORCER		150
#define UNITMAP_DRAKES_FIGHTER		160
#define UNITMAP_DRAKES_FIRE			170
#define UNITMAP_DRAKES_FLAMEHEART	180
#define UNITMAP_DRAKES_FLARE		190
#define UNITMAP_DRAKES_THRASHER		200
#define UNITMAP_DRAKES_GLIDER		210
#define UNITMAP_DRAKES_HURRICANE	220
#define UNITMAP_DRAKES_INFERNO		230
#define UNITMAP_DRAKES_SKY			240
#define UNITMAP_DRAKES_ARBITER		250
#define UNITMAP_DRAKES_WARDEN		260
#define UNITMAP_DRAKES_WARRIOR		270

#define UNITMAP_DWARVES_DWARVES		300
#define UNITMAP_DWARVES_BERSERKER	310
#define UNITMAP_DWARVES_DRAGONGUARD	320
#define UNITMAP_DWARVES_FIGHTER		330
#define UNITMAP_DWARVES_GRYPHON_MASTER	340
#define UNITMAP_DWARVES_GRYPHON_RIDER	350
#define UNITMAP_DWARVES_GUARD		360
#define UNITMAP_DWARVES_LORD		370
#define UNITMAP_DWARVES_RUNEMASTER	380
#define UNITMAP_DWARVES_SENTINEL	390
#define UNITMAP_DWARVES_STALWART	400
#define UNITMAP_DWARVES_STEELCLAD	410
#define UNITMAP_DWARVES_THUNDERER	420
#define UNITMAP_DWARVES_THUNDERGUARD	430
#define UNITMAP_DWARVES_ULFSERKER	440

#define UNITMAP_ELVES_ELVES1		490
#define UNITMAP_ELVES_ELVES2		500
#define UNITMAP_ELVES_ARCHER		510
#define UNITMAP_ELVES_ARCHER_FEMALE	520
#define UNITMAP_ELVES_AVENGER		530
#define UNITMAP_ELVES_AVENGER_FEMALE	540
#define UNITMAP_ELVES_CAPTAIN		550
#define UNITMAP_ELVES_CHAMPION		560
#define UNITMAP_ELVES_DRUID			570
#define UNITMAP_ELVES_ENCHANTRESS	580
#define UNITMAP_ELVES_FIGHTER		590
#define UNITMAP_ELVES_HERO			600
#define UNITMAP_ELVES_HIGH_LORD		610
#define UNITMAP_ELVES_LORD			620
#define UNITMAP_ELVES_MARKSMAN		630
#define UNITMAP_ELVES_MARKSMAN_FEMALE	640
#define UNITMAP_ELVES_MARSHAL		650
#define UNITMAP_ELVES_OUTRIDER		660
#define UNITMAP_ELVES_RANGER		670
#define UNITMAP_ELVES_RANGER_FEMALE	680
#define UNITMAP_ELVES_RIDER			690
#define UNITMAP_ELVES_SCOUT			700
#define UNITMAP_ELVES_SHAMAN		710
#define UNITMAP_ELVES_SHARPSHOOTER	720
#define UNITMAP_ELVES_SHARPSHOOTER_FEMALE	730
#define UNITMAP_ELVES_SHYDE			740
#define UNITMAP_ELVES_SORCERESS		750
#define UNITMAP_ELVES_SYLPH			760

#define UNITMAP_GOBLINS_GOBLINS		800
#define UNITMAP_GOBLINS_DIREWOLVER	810
#define UNITMAP_GOBLINS_IMPALER		820
#define UNITMAP_GOBLINS_KNIGHT		830
#define UNITMAP_GOBLINS_PILLAGER	840
#define UNITMAP_GOBLINS_ROUSER		850
#define UNITMAP_GOBLINS_SPEARMAN	860
#define UNITMAP_GOBLINS_WOLF_RIDER	870

#define UNITMAP_HUMANLOYALISTS_HUMANLOYALISTS	900
#define UNITMAP_HUMANLOYALISTS_BOWMAN			910
#define UNITMAP_HUMANLOYALISTS_CAVALIER			920
#define UNITMAP_HUMANLOYALISTS_CAVALRYMAN		930
#define UNITMAP_HUMANLOYALISTS_DRAGOON			940
#define UNITMAP_HUMANLOYALISTS_DUELIST			950
#define UNITMAP_HUMANLOYALISTS_FENCER			960
#define UNITMAP_HUMANLOYALISTS_GENERAL			970
#define UNITMAP_HUMANLOYALISTS_GRAND_KNIGHT		980
#define UNITMAP_HUMANLOYALISTS_HALBERDIER		990
#define UNITMAP_HUMANLOYALISTS_HEAVYINFANTRY	1000
#define UNITMAP_HUMANLOYALISTS_HORSEMAN			1010
#define UNITMAP_HUMANLOYALISTS_JAVELINEER		1020
#define UNITMAP_HUMANLOYALISTS_KNIGHT			1030
#define UNITMAP_HUMANLOYALISTS_LANCER			1040
#define UNITMAP_HUMANLOYALISTS_LIEUTENANT		1050
#define UNITMAP_HUMANLOYALISTS_LONGBOWMAN		1060
#define UNITMAP_HUMANLOYALISTS_MARSHAL			1070
#define UNITMAP_HUMANLOYALISTS_MASTER_AT_ARMS	1080
#define UNITMAP_HUMANLOYALISTS_MASTERBOWMAN		1090
#define UNITMAP_HUMANLOYALISTS_PALADIN			1100
#define UNITMAP_HUMANLOYALISTS_PIKEMAN			1110
#define UNITMAP_HUMANLOYALISTS_ROYAL_WARRIOR	1120
#define UNITMAP_HUMANLOYALISTS_ROYALGUARD		1130
#define UNITMAP_HUMANLOYALISTS_SERGEANT			1140
#define UNITMAP_HUMANLOYALISTS_SHOCKTROOPER		1150
#define UNITMAP_HUMANLOYALISTS_SIEGETROOPER		1160
#define UNITMAP_HUMANLOYALISTS_SPEARMAN			1170
#define UNITMAP_HUMANLOYALISTS_SWORDSMAN		1180

#define UNITMAP_HUMANMAGI_HUMANMAGI		1200
#define UNITMAP_HUMANMAGI_ARCH_MAGE		1210
#define UNITMAP_HUMANMAGI_ARCH_MAGE_FEMALE	1220
#define UNITMAP_HUMANMAGI_ELDER_MAGE	1230
#define UNITMAP_HUMANMAGI_GREAT_MAGE	1240
#define UNITMAP_HUMANMAGI_GREAT_MAGE_FEMALE	1250
#define UNITMAP_HUMANMAGI_MAGE		1260
#define UNITMAP_HUMANMAGI_MAGE_FEMALE	1270
#define UNITMAP_HUMANMAGI_RED_MAGE	1280
#define UNITMAP_HUMANMAGI_RED_MAGE_FEMALE	1290
#define UNITMAP_HUMANMAGI_SILVER_MAGE	1300
#define UNITMAP_HUMANMAGI_SILVER_MAGE_FEMALE	1310
#define UNITMAP_HUMANMAGI_WHITE_CLERIC	1320
#define UNITMAP_HUMANMAGI_WHITE_CLERIC_FEMALE	1330
#define UNITMAP_HUMANMAGI_WHITE_MAGE	1340
#define UNITMAP_HUMANMAGI_WHITE_MAGE_FEMALE	1350

#define UNITMAP_HUMANOUTLAWS_HUMANOUTLAWS		1400
#define UNITMAP_HUMANOUTLAWS_ASSASSIN			1410
#define UNITMAP_HUMANOUTLAWS_ASSASSIN_FEMALE	1420
#define UNITMAP_HUMANOUTLAWS_BANDIT				1430
#define UNITMAP_HUMANOUTLAWS_FOOTPAD			1440
#define UNITMAP_HUMANOUTLAWS_FUGITIVE			1450
#define UNITMAP_HUMANOUTLAWS_FUGITIVE_FEMALE	1460
#define UNITMAP_HUMANOUTLAWS_HIGHWAYMAN			1470
#define UNITMAP_HUMANOUTLAWS_HUNTSMAN			1480
#define UNITMAP_HUMANOUTLAWS_OUTLAW				1490
#define UNITMAP_HUMANOUTLAWS_OUTLAW_FEMALE		1500
#define UNITMAP_HUMANOUTLAWS_POACHER			1510
#define UNITMAP_HUMANOUTLAWS_RANGER				1520
#define UNITMAP_HUMANOUTLAWS_ROGUE				1530
#define UNITMAP_HUMANOUTLAWS_ROGUE_FEMALE		1540
#define UNITMAP_HUMANOUTLAWS_THIEF				1550
#define UNITMAP_HUMANOUTLAWS_THIEF_FEMALE		1560
#define UNITMAP_HUMANOUTLAWS_THUG				1570
#define UNITMAP_HUMANOUTLAWS_TRAPPER			1580
#define UNITMAP_HUMANOUTLAWS_FOOTPAD_FEMALE		1590

#define UNITMAP_HUMANPEASANTS_HUMANPEASANTS		1600
#define UNITMAP_HUMANPEASANTS_PEASANT			1610
#define UNITMAP_HUMANPEASANTS_RUFFIAN			1620
#define UNITMAP_HUMANPEASANTS_WOODSMAN			1630

#define UNITMAP_MERFOLK_MERFOLK		1700
#define UNITMAP_MERFOLK_INITIATE	1710

#define UNITMAP_MONSTERS_CAVESPIDER		1800
#define UNITMAP_MONSTERS_CUTTLEFISH		1810
#define UNITMAP_MONSTERS_DEEP_TENTACLE	1820
#define UNITMAP_MONSTERS_FIRE_DRAGON	1830
#define UNITMAP_MONSTERS_GIANT_MUDCRAWLER	1840
#define UNITMAP_MONSTERS_GRYPHON		1850
#define UNITMAP_MONSTERS_MUDCRAWLER		1860
#define UNITMAP_MONSTERS_SCORPION		1870
#define UNITMAP_MONSTERS_SEASERPENT		1880
#define UNITMAP_MONSTERS_SKELETAL_DRAGON	1890
#define UNITMAP_MONSTERS_WOLF			1900
#define UNITMAP_MONSTERS_YETI			1910

#define UNITMAP_NAGAS_NAGAS				2000
#define UNITMAP_NAGAS_FIGHTER			2010
#define UNITMAP_NAGAS_MYRMIDON			2020
#define UNITMAP_NAGAS_WARRIOR			2030

#define UNITMAP_OGRES_OGRE				2100
#define UNITMAP_OGRES_YOUNG_OGRE		2110

#define UNITMAP_ORCS_ORCS		2200
#define UNITMAP_ORCS_ARCHER		2210
#define UNITMAP_ORCS_ASSASSIN	2220
#define UNITMAP_ORCS_GRUNT		2230
#define UNITMAP_ORCS_LEADER		2240
#define UNITMAP_ORCS_RULER		2250
#define UNITMAP_ORCS_SLAYER		2260
#define UNITMAP_ORCS_SLURBOW	2270
#define UNITMAP_ORCS_SOVEREIGN	2280
#define UNITMAP_ORCS_WARLORD	2290
#define UNITMAP_ORCS_WARRIOR	2300
#define UNITMAP_ORCS_XBOWMAN	2310

#define UNITMAP_SAURIANS_SAURIANS	2400
#define UNITMAP_SAURIANS_AMBUSHER	2410
#define UNITMAP_SAURIANS_AUGUR		2420
#define UNITMAP_SAURIANS_FLANKER	2430
#define UNITMAP_SAURIANS_ORACLE		2440
#define UNITMAP_SAURIANS_SKIRMISHER	2450
#define UNITMAP_SAURIANS_SOOTHSAYER	2460

#define UNITMAP_TRANSPORT	2470

#define UNITMAP_TROLLS_TROLLS	2500
#define UNITMAP_TROLLS_GRUNT	2510
#define UNITMAP_TROLLS_LOBBER	2520
#define UNITMAP_TROLLS_SHAMAN	2530
#define UNITMAP_TROLLS_WARRIOR	2540
#define UNITMAP_TROLLS_WHELP	2550

#define UNITMAP_UNDEAD_BAT			2560
#define UNITMAP_UNDEAD_BLOODBAT		2570
#define UNITMAP_UNDEAD_DREADBAT		2580
#define UNITMAP_UNDEAD_GHOST		2590
#define UNITMAP_UNDEAD_GHOUL		2600
#define UNITMAP_UNDEAD_NECROPHAGE	2610
#define UNITMAP_UNDEAD_NIGHTGAUNT	2620
#define UNITMAP_UNDEAD_SHADOW		2630
#define UNITMAP_UNDEAD_SOULLESS_DRAKE	2640
#define UNITMAP_UNDEAD_SOULLESS_DWARF	2650
#define UNITMAP_UNDEAD_SOULLESS_MOUNTED	2660
#define UNITMAP_UNDEAD_SOULLESS_SAURIAN	2670
#define UNITMAP_UNDEAD_SOULLESS_SWIMMER	2680
#define UNITMAP_UNDEAD_SOULLESS_TROLL	2690
#define UNITMAP_UNDEAD_SOULLESS_WOSE	2700
#define UNITMAP_UNDEAD_SOULLESS			2710
#define UNITMAP_UNDEAD_SPECTRE			2720
#define UNITMAP_UNDEAD_WRAITH			2730
#define UNITMAP_UNDEAD_ZOMBIE_BAT		2740
#define UNITMAP_UNDEAD_ZOMBIE_DRAKE		2750
#define UNITMAP_UNDEAD_ZOMBIE_DWARF		2760
#define UNITMAP_UNDEAD_ZOMBIE_MOUNTED	2770
#define UNITMAP_UNDEAD_ZOMBIE_SAURIAN	2780
#define UNITMAP_UNDEAD_ZOMBIE_SWIMMER	2790
#define UNITMAP_UNDEAD_ZOMBIE_TROLL		2800
#define UNITMAP_UNDEAD_ZOMBIE_WOSE		2810
#define UNITMAP_UNDEAD_ZOMBIE			2820

#define UNITMAP_NECROMANCERS_NECROMANCERS	2830
#define UNITMAP_NECROMANCERS_ADEPT			2840
#define UNITMAP_NECROMANCERS_ADEPT_FEMALE	2850
#define UNITMAP_NECROMANCERS_ANCIENT_LICH	2860
#define UNITMAP_NECROMANCERS_DARK_SORCERER	2870
#define UNITMAP_NECROMANCERS_DARK_SORCERER_FEMALE	2880
#define UNITMAP_NECROMANCERS_LICH			2890
#define UNITMAP_NECROMANCERS_NECROMANCER	2900
#define UNITMAP_NECROMANCERS_NECROMANCER_FEMALE	2910

#define UNITMAP_SKELETAL_SKELETAL	2920
#define UNITMAP_SKELETAL_ARCHER		2930
#define UNITMAP_SKELETAL_BANEBOW	2940
#define UNITMAP_SKELETAL_BONE_SHOOTER	2950
#define UNITMAP_SKELETAL_CHOCOBONE	2960
#define UNITMAP_SKELETAL_DEATHBLADE	2970
#define UNITMAP_SKELETAL_DEATHKNIGHT	2980
#define UNITMAP_SKELETAL_DRAUG		2990
#define UNITMAP_SKELETAL_REVENANT	3000
#define UNITMAP_SKELETAL_SKELETON	3010

#define UNITMAP_WOSES_WOSES		3020
#define UNITMAP_WOSES_ANCIENT	3030
#define UNITMAP_WOSES_ELDER		3040
#define UNITMAP_WOSES_WOSE		3050

// Descent into Darkness
#define UNITMAP_DID_APPRENTICE_MAGE		3060
#define UNITMAP_DID_APPRENTICE_NECROMANCER	3070
#define UNITMAP_DID_DARK_MAGE			3080
#define UNITMAP_DID_GHAST_RAT			3090
#define UNITMAP_DID_NEUTRAL_OUTLAW_PRINCESS	3100

// Eastern Invasion
#define UNITMAP_EI_OWAEC		3110

// Heir to the Throne
#define UNITMAP_HTTT_GRYPHON_SEA_ORC	3120
#define UNITMAP_HTTT_HUMAN_BATTLEPRINCESS	3130
#define UNITMAP_HTTT_HUMAN_PRINCESS			3140
#define UNITMAP_HTTT_HUMAN_QUEEN			3150
#define UNITMAP_HTTT_KONRAD_COMMANDER_SCEPTER	3160
#define UNITMAP_HTTT_KONRAD_COMMANDER		3170
#define UNITMAP_HTTT_KONRAD_FIGHTER			3180
#define UNITMAP_HTTT_KONRAD_LORD_SCEPTER	3190
#define UNITMAP_HTTT_KONRAD_LORD			3200

// Liberty
#define UNITMAP_LIBERTY_SKELETAL		3210
#define UNITMAP_LIBERTY_ROGUE_MAGE		3220
#define UNITMAP_LIBERTY_SHADOW_LORD		3230
#define UNITMAP_LIBERTY_SHADOW_MAGE		3240

// Sceptre of Fire
#define UNITMAP_SOF_DWARVES			3250
#define UNITMAP_SOF_HALDRIC_II		3260

// Son of the Black Eye
#define UNITMAP_SOTBE_UNITS			3270

// The Hammer of Thursagan
#define UNITMAP_THOT_ANNALIST		3280
#define UNITMAP_THOT_KARRAG			3290
#define UNITMAP_THOT_LOREMASTER		3300
#define UNITMAP_THOT_MASKED_DRAGONGUARD	3310
#define UNITMAP_THOT_MASKED_FIGHTER	3320
#define UNITMAP_THOT_MASKED_GUARD	3330
#define UNITMAP_THOT_MASKED_LORD	3340
#define UNITMAP_THOT_MASKED_SENTINEL	3350
#define UNITMAP_THOT_MASKED_STALWART	3360
#define UNITMAP_THOT_MASKED_STEELCLAD	3370
#define UNITMAP_THOT_MASKED_THUNDERER	3380
#define UNITMAP_THOT_MASKED_THUNDERGUARD	3390
#define UNITMAP_THOT_WITNESS			3400

// The Rise of Wesnoth
#define UNITMAP_TROW_NOBLE_COMMANDER	3410
#define UNITMAP_TROW_NOBLE_FIGHTER		3420
#define UNITMAP_TROW_NOBLE_LORD			3430
#define UNITMAP_TROW_NOBLE_YOUTH_UNDEAD	3440
#define UNITMAP_TROW_WESFOLK_LADY_MASKED	3450
#define UNITMAP_TROW_WESFOLK_LADY		3460
#define UNITMAP_TROW_WESFOLK_LEADER_MASKED	3470
#define UNITMAP_TROW_WESFOLK_LEADER		3480
#define UNITMAP_TROW_WESFOLK_OUTCAST_MASKED	3490
#define UNITMAP_TROW_WESFOLK_OUTCAST	3500
#define UNITMAP_TROW_WOSE_SAPLING		3510

// The South Guard
#define UNITMAP_TSG_COMMANDER		3520
#define UNITMAP_TSG_EYESTALK		3530


// Tutorial
#define UNITMAP_TUTORIAL_HUMAN_PRINCESS	3540
#define UNITMAP_TUTORIAL_KONRAD_FIGHTER	3550
#define UNITMAP_TUTORIAL_QUINTAIN		3560

// Under the Burning Suns
#define UNITMAP_UTBS_ALIEN			3570
#define UNITMAP_UTBS_DWARVES_EXPLORER	3580
#define UNITMAP_UTBS_DWARVES_PATHFINDER	3590
#define UNITMAP_UTBS_DWARVES_SCOUT		3600
#define UNITMAP_UTBS_ELVES_ELVES		3610
#define UNITMAP_UTBS_ELVES_ARCHER		3620
#define UNITMAP_UTBS_ELVES_ARCHER_FEMALE	3630
#define UNITMAP_UTBS_ELVES_AVENGER		3640
#define UNITMAP_UTBS_ELVES_AVENGER_FEMALE	3650
#define UNITMAP_UTBS_ELVES_CAPTAIN		3660
#define UNITMAP_UTBS_ELVES_CHAMPION		3670
#define UNITMAP_UTBS_ELVES_CORRUPTED_ELF	3680
#define UNITMAP_UTBS_ELVES_DRUID_ELOH	3690
#define UNITMAP_UTBS_ELVES_FIGHTER		3700
#define UNITMAP_UTBS_ELVES_HERO			3710
#define UNITMAP_UTBS_ELVES_HORSEMAN		3720
#define UNITMAP_UTBS_ELVES_HUNTER		3730
#define UNITMAP_UTBS_ELVES_HUNTER_FEMALE	3740
#define UNITMAP_UTBS_ELVES_KALEH		3750
#define UNITMAP_UTBS_ELVES_MARKSMAN		3760
#define UNITMAP_UTBS_ELVES_MARKSMAN_FEMALE	3770
#define UNITMAP_UTBS_ELVES_MARSHAL		3780
#define UNITMAP_UTBS_ELVES_NYM			3790
#define UNITMAP_UTBS_ELVES_OUTRIDER		3800
#define UNITMAP_UTBS_ELVES_PROWLER		3810
#define UNITMAP_UTBS_ELVES_RANGER		3820
#define UNITMAP_UTBS_ELVES_RANGER_FEMALE	3830
#define UNITMAP_UTBS_ELVES_RIDER		3840
#define UNITMAP_UTBS_ELVES_SCOUT		3850
#define UNITMAP_UTBS_ELVES_SENTINEL		3860
#define UNITMAP_UTBS_ELVES_SHAMAN		3870
#define UNITMAP_UTBS_ELVES_SHARPSHOOTER	3880
#define UNITMAP_UTBS_ELVES_SHARPSHOOTER_FEMALE	3890
#define UNITMAP_UTBS_ELVES_SHYDE		3900
#define UNITMAP_UTBS_HUMAN_COMMANDER	3910
#define UNITMAP_UTBS_MONSTERS_DAWARF_DEMON	3920
#define UNITMAP_UTBS_MONSTERS_FIREGHOST		3930
#define UNITMAP_UTBS_MONSTERS_MONSTERS		3940
#define UNITMAP_UTBS_NAGAS_NAGAS		3950
#define UNITMAP_UTBS_NAGAS_HUNTER		3960
#define UNITMAP_UTBS_ORCS_NIGHTSTALKER	3970
#define UNITMAP_UTBS_UNDEAD				3980

// The South Guard missing files
#define UNITMAP_TSG_DISMOUNTED_COMMANDER	3990
#define UNITMAP_TSG_HORSEMAN_COMMANDER		4000
#define UNITMAP_TSG_JUNIOR_COMMANDER		4010
#define UNITMAP_TSG_MOUNTED_GENERAL			4020

#define UNITMAP_BLANK		4030

#define UNITMAP_ELLIPSE		4040

// Invasion from the Unknown
#define UNITMAP_IFTU_ALIEN_PSY		4050
#define UNITMAP_IFTU_ALIEN_VERLISSH	4060
#define UNITMAP_IFTU_DEMONS			4070
#define UNITMAP_IFTU_DWARVES		4080
#define UNITMAP_IFTU_ELVES			4090
#define UNITMAP_IFTU_FAIRIES_SYLVAN	4100
#define UNITMAP_IFTU_FAKE			4110
#define UNITMAP_IFTU_GOBLINS		4120
#define UNITMAP_IFTU_GRYPHONS		4130
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_ARCHER	4140
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_CAPTAIN	4150
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_EAGLE_RIDER	4160
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_FLAGBEARER	4170
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_GREATBOW		4180
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_GUARD			4190
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_GUARDIAN		4200
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI				4210
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_LANCER		4220
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_LONGSWORDSMAN	4230
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_PIKEMAN		4240
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SCOUT			4250
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SHIELD_GUARD	4260
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SILVER_SHIELD	4270
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SLAYER		4280
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SPEARMAN		4290
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_STRONGBOW		4300
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SWORDMAN		4310
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_SWORDMASTER	4320
#define UNITMAP_IFTU_HUMAN_ARAGWAITHI_WARLOCK		4330
#define UNITMAP_IFTU_HUMAN_CHAOS_DARK_KNIGHT		4340
#define UNITMAP_IFTU_HUMAN_CHAOS_INVADER			4350
#define UNITMAP_IFTU_HUMAN_CHAOS					4360
#define UNITMAP_IFTU_HUMAN_CHAOS_RAZERMAN			4370
#define UNITMAP_IFTU_HUMAN_PEASANTS					4380
#define UNITMAP_IFTU_IMPS							4390
#define UNITMAP_IFTU_MECHANICAL						4400
#define UNITMAP_IFTU_MONSTERS						4410
#define UNITMAP_IFTU_MONSTERS2						4420
#define UNITMAP_IFTU_MONSTERS3						4430
#define UNITMAP_IFTU_MONSTERS4						4440
#define UNITMAP_IFTU_MONSTERS5						4450
#define UNITMAP_IFTU_ORCS							4460
#define UNITMAP_IFTU_SHAXTHAL						4470
#define UNITMAP_IFTU_SPIRITS_ANIMATED_ROCK			4480
#define UNITMAP_IFTU_SPIRITS_FIRE					4490
#define UNITMAP_IFTU_SPIRITS_FIREWISP				4500
#define UNITMAP_IFTU_SPIRITS_ROCK_GOLEM				4510
#define UNITMAP_IFTU_SPIRITS_WATER					4520
#define UNITMAP_IFTU_TROLLS							4530
#define UNITMAP_IFTU_UNDEAD_SKELETAL				4540
#define UNITMAP_IFTU_UNDEAD							4550

// Dead Water
#define UNITMAP_DEADWATER_BRAWLER					4560
#define UNITMAP_DEADWATER_CHILD_KING				4570
#define UNITMAP_DEADWATER_CITIZEN					4580
#define UNITMAP_DEADWATER_DARK_SHAPE				4590
#define UNITMAP_DEADWATER_FIREGHOST					4600
#define UNITMAP_DEADWATER_KRAKEN					4610
#define UNITMAP_DEADWATER_SOLDIER_KING				4620
#define UNITMAP_DEADWATER_WARRIOR_KING				4630
#define UNITMAP_DEADWATER_YOUNG_KING				4640

// FLAGS
#define MAP_BLACK_FLAG			4650
#define MAP_FLAG				4660
#define MAP_KNALGAN_FLAG		4670
#define MAP_LOYALIST_FLAG		4680
#define MAP_SG_FLAG				4690
#define MAP_UNDEAD_FLAG			4700


// HALOS (do not need palette swapping, but keep the +10 spacing
#define HALOMAP_ELVEN_DRUID_HEALING				4710
#define HALOMAP_ELVEN_ELVEN_SHIELD				4720
#define HALOMAP_ELVEN_FAERIE_FIRE				4730
#define HALOMAP_ELVEN_ICE_HALO					4740
#define HALOMAP_ELVEN_NATURE_HALO				4750
#define HALOMAP_ELVEN_SHAMAN_HEAL				4760
#define HALOMAP_ELVEN_SHYDE						4770
#define HALOMAP_FIRE_AURA						4780
#define HALOMAP_FLAME_BURST						4790
#define HALOMAP_HOLY_HALO						4800
#define HALOMAP_HOLY_LIGHTBEAM					4810
#define HALOMAP_IFTU_AVATAR						4820
#define HALOMAP_IFTU_BOMB_EXPLODE				4830
#define HALOMAP_IFTU_CHAOS						4840
#define HALOMAP_IFTU_DARKNESS_BEAM				4850
#define HALOMAP_IFTU_ELYNIA_NOILLUM				4860
#define HALOMAP_IFTU_ELYNIA						4870
#define HALOMAP_IFTU_ILLUMINATES				4880
#define HALOMAP_IFTU_OBSCURES					4890
#define HALOMAP_IFTU_WOSE_RANGED				4900
#define HALOMAP_IFTU_WOSE						4910
#define HALOMAP_ILLUMINATES_AURA				4920
#define HALOMAP_LIBERTY_SHADOW_MAGE				4930
#define HALOMAP_LIGHTHOUSE_AURA					4940
#define HALOMAP_LIGHTNING_BOLT					4950
#define HALOMAP_MAGE_HALO_BIG					4960
#define HALOMAP_MAGE_HALO						4970
#define HALOMAP_MAGE_PREPARATION				4980
#define HALOMAP_MERFOLK_STAFF_FLARE				4990
#define HALOMAP_MERFOLK_WATER					5000
#define HALOMAP_SAURIAN_MAGIC_HALO				5010
#define HALOMAP_TELEPORT						5020
#define HALOMAP_THOT_KARRAG						5030
#define HALOMAP_UNDEAD							5040


// Oooze Mini-Campaign
#define UNITMAP_OOZE_GIANT_MUDCRAWLER			5050
#define UNITMAP_OOZE_HUMAN_QUEEN				5060
#define UNITMAP_OOZE_MUDCRAWLER					5070
#define UNITMAP_OOZE_OLDELVISH_ENCHANTRESS		5080
#define UNITMAP_OOZE_OLDELVISH_SHAMAN			5090
#define UNITMAP_OOZE_OLDELVISH_SORCERESS		5100
#define UNITMAP_OOZE_OLDELVISH_SYLPH			5110
#define UNITMAP_OOZE_QUINTAIN					5120

// SurvivalXtreme
#define UNITMAP_SX_SAND_SCORPION				5130

// The Dark Hordes
#define UNITMAP_TDH								5140


#define NUM_UNITMAPS		5150




#include "SDL.h"
#include <string>

void checkUnitTextureAtlas(void);
void initUnitTextureAtlas(void);
void freeUnitTextureAtlas(void);
bool getUnitTextureAtlasInfo(const std::string& filename, const std::string& modifications, textureAtlasInfo &tinfo);


#endif // UNIT_TEXTURE_ATLAS_INCLUDED
